version: '2'
services: 
  frontend:
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile
    container_name: frontend_container
    ports:
      - 8080:8080
    volumes: 
      - .:/app/home
    tty: true